# Generated by Django 6.0.5 on 2026-05-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoingrediente',
            name='cantidad_producida',
        ),
    ]
