# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_productoingrediente_cantidad_producida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoingrediente',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoingrediente',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoingrediente',
            name='stock_posterior',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
