# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_vencimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
